# config.yaml
# Arquivo de Configuração Central para o Projeto Pró-Vida

# 1. Configuração do Provedor de LLM
llm_provider: google

# 2. Alocação Estratégica de Modelos
models:
  planning_agent: 'gemini-2.5-pro'
  analysis_agent: 'gemini-2.5-pro'
  synthesis_agent: 'gemini-2.5-pro'
  rag_query_agent: 'gemini-2.5-flash'
  chat_agent: 'gemini-2.5-flash'
  translation_agent: 'gemini-2.5-flash-lite'
  keyword_extraction_agent: 'gemini-2.5-flash-lite'

# 3. Parâmetros de Pesquisa e Automação
research_parameters:
  deep_research_max_searches: 100
  scheduled_curation:
    enabled: true
    schedule: "0 5 * * *" # Todo dia às 5:00 AM
    max_duration_minutes: 60
  conflict_review_days: 90

# 4. Configuração dos Serviços de Backend
services:
  neo4j_knowledge:
    uri: "${NEO4J_URI:-bolt://localhost:7687}"
    user: "neo4j"
    password: "${NEO4J_PASSWORD}"
    database: "provida-knowledge"
  
  neo4j_memory_agents:
    uri: "${NEO4J_URI:-bolt://localhost:7687}"
    user: "neo4j"
    password: "${NEO4J_PASSWORD}"
    database: "provida-memory"

  minio_s3:
    endpoint: "${MINIO_ENDPOINT:-localhost:9000}"
    access_key: "${MINIO_ACCESS_KEY}"
    secret_key: "${MINIO_SECRET_KEY}"
    bucket_name: "pro-vida-articles"

  vector_db:
    provider: "chromadb"
    path: "${VECTOR_DB_PATH:-./chroma_db}"
