# Application Configuration
app:
  name: Provida
  version: 1.0.0
  debug: false

# Database Configuration
database:
  neo4j:
    knowledge:
      uri: bolt://neo4j:7687
      user: neo4j
      password: ${NEO4J_PASSWORD}
      database: provida-knowledge
    memory_agents:
      uri: bolt://neo4j:7687
      user: neo4j
      password: ${NEO4J_PASSWORD}
      database: provida-memory

# MinIO Configuration
minio:
  access_key: ${MINIO_ACCESS_KEY}
  secret_key: ${MINIO_SECRET_KEY}
  endpoint: http://minio:9000

# Google API Configuration
google:
  api_key: ${GOOGLE_API_KEY}

# RAG specific settings
rag:
  n_results: 5

# Search Configuration
search:
  deep_search_limit: 100  # Default limit for deep search mode
  timeout: 30  # Timeout in seconds for search requests
  api_key: ${SEARCH_API_KEY}  # API key for search service
  endpoint: ${SEARCH_ENDPOINT}  # Endpoint for search service
  rate_limit: 10  # Number of requests per minute
  
  # Models Configuration
  models:
    llm:
      enabled: true  # Enable or disable LLM
      api_key: ${LLM_API_KEY}  # API key for LLM service
      endpoint: ${LLM_ENDPOINT}  # Endpoint for LLM service
      timeout: 30  # Timeout in seconds for LLM requests
  
  # Reporting Configuration
  reporting:
    enabled: true  # Enable or disable reporting
    interval: 86400  # Interval in seconds between report generations (1 day)
    formats:
      - pdf
      - csv
    output_path: /path/to/reports  # Path where reports will be saved
  
  # Automation Configuration
  automation:
    enabled: true  # Enable or disable automation
    interval: 3600  # Interval in seconds between automation runs
    daily_update_cron: "0 5 * * *" # Daily update at 5 AM
    quarterly_review_cron: "0 6 1 */3 *" # Quarterly review on 1st day of Jan, Apr, Jul, Oct at 6 AM

# Logging Configuration
logging:
  level: INFO # Global logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  console_output: true # Enable/disable console output
  file_output:
    enabled: true
    path: "logs/application.log" # Main application log file
    max_bytes: 10485760 # 10 MB
    backup_count: 5
  system_log: # Specific log for autonomous decisions
    enabled: true
    path: "logs/system_log.txt"
    level: INFO # Specific level for system_log (e.g., INFO, DEBUG)